<?php
$form->setAttribute(
    'action', $this->url(
    'device', array(
        'action' => 'add'
    )
)
);
$form->prepare();
?>
<div class="row">
    <h1 class="col-md-12">Device Registration</h1>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php echo $this->form()->openTag($form); ?>
        <?php echo $this->formRow($form->get('name')); ?>
        <?php echo $this->formRow($form->get('description')); ?>
        <div class="form-group">
            <label class="col-sm-2 control-label">Location</label>

            <div class="col-sm-10"><input type="text" class="form-control"
                                          id="location_placeholder">
            </div>
            <div id="picker" class="col-sm-10 col-sm-offset-2"
                 style="height: 400px;"></div>
        </div>
        <?php echo $this->formRow($form->get('lat')); ?>
        <?php echo $this->formRow($form->get('lng')); ?>
        <?php echo $this->formHidden($form->get('id')); ?>
        <?php echo $this->formRow($form->get('send')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>

<script type="text/javascript"
        src='http://maps.google.com/maps/api/js?sensor=false&libraries=places'></script>
<script src="<?php echo $this->basePath(
    '/js/locationpicker.jquery.min.js'
); ?>"></script>
<script>
    $(function () {
        $('button[type="submit"]')
            .attr('disabled', 'disabled');
        $('#picker').locationpicker({
            location: {latitude: 21.0277644, longitude: 105.83415979999995},
            inputBinding: {
                latitudeInput: $('#lat_placeholder'),
                longitudeInput: $('#lng_placeholder'),
                locationNameInput: $('#location_placeholder')
            },
            enableAutocomplete: true,
            onchanged: function(currentLocation, radius, isMarkerDropped) {
                if ($('#lat_placeholder').val != '' && $('#lng_placeholder').val != '') {
                    $('button[type="submit"]').removeAttr('disabled');
                }
            }
        })
    });

</script>