<?php
/**
 * Created by PhpStorm.
 * User: yoshii
 * Date: 2015/03/09
 * Time: 18:33
 */
?>
<h1><?php echo $this->device->name; ?>
    <small><?php echo $this->device->description; ?></small>
</h1>
<div class="row">
    <div class="col-md-12" id="map-container" style="height: 300px">
    </div>
</div>
<div class="row">
    <div class="col-md-12" id="chart-container">
        <canvas id="chart"></canvas>
        <div id="legend" class="text-center"></div>
    </div>
</div>

<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.1/Chart.js"></script>
<script type="text/javascript"
        src='http://maps.google.com/maps/api/js?sensor=false&libraries=places'></script>
<script src="<?php echo $this->basePath(
    '/js/jquery.googlemap.js'
); ?>"></script>
<script>
    $(function () {
        var api = '<?php echo $this->url('web_api', ['action'=>'data','id'=>$this->device->id]); ?>';
        $.get(
            api,
            function (json) {
                var ctx = $("#chart").get(0).getContext("2d");
                var opt = {
                    responsive: true,
                    maintainAspectRatio: true,
                    scaleShowGridLines: true,
                    scaleGridLineColor: "rgba(0,0,0,.05)",
                    scaleGridLineWidth: 1,
                    scaleShowHorizontalLines: true,
                    scaleShowVerticalLines: true,
                    bezierCurve: true,
                    bezierCurveTension: 0.4,
                    pointDot: true,
                    pointDotRadius: 4,
                    pointDotStrokeWidth: 1,
                    pointHitDetectionRadius: 20,
                    datasetStroke: true,
                    datasetStrokeWidth: 2,
                    datasetFill: true,
                    tooltipTemplate: "<%if (label){%><%=label%>: <%}%><%= value %>",
                    legendTemplate: "<ul class=\"list-inline\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].strokeColor%>\"><%if(datasets[i].label){%><%=datasets[i].label%><%}%></span></li><%}%></ul>"
                };
                var chart = new Chart(ctx).Line(json, opt);
                document.getElementById('legend').innerHTML = chart.generateLegend();
            });
        $("#map-container")
            .googleMap()
            .addMarker({
                coords: [<?php echo $this->device->lat; ?>, <?php echo $this->device->lng; ?>],
                title: '<?php echo $this->device->name; ?>',
                text: '<?php echo $this->device->description; ?>'
            });
    });
</script>
