
<div class="row">
    <h1 class="col-md-12">Main Menu</h1>
    <div class="col-md-12 text-right">
        <span>Logged-in as: <?php echo $this->identity(); ?></span> <a
            class="btn btn-danger" href="<?php echo $this->url('logout'); ?>">
            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
            logout</a>
    </div>
</div>

<div class="row">
    <h2 class="col-md-12">Registered Field Devices</h2>
    <div class="col-md-12 text-right">
        <a class="btn btn-primary"
            href="<?php echo $this->url('device', ['action'=>'add']); ?>">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            Add</a>
    </div>
    <div class="col-md-12">
        <table class="table table-striped">
            <tr>
                <th>ID</th>
                <th>Device Name</th>
                <th>Description</th>
                <th>Operation</th>
            </tr>
            <?php foreach($devices as $device): ?>
            <tr>
                <td><?php echo $device->id; ?></td>
                <td><?php echo $device->name; ?></td>
                <td><?php echo $device->description; ?></td>
                <td class="text-right">
                    <a class="btn btn-primary"
                    href="<?php echo $this->url('device', ['action'=>'view', 'id'=>$device->id]);?>">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                        View</a>
                    <a class="btn btn-info"
                       href="<?php echo $this->url(
                           'device', ['action' => 'edit', 'id' => $device->id]
                       ); ?>">
                        <span class="glyphicon glyphicon-edit"
                              aria-hidden="true"></span>
                        Edit</a>

                    <a class="btn btn-warning"
                    href="<?php echo $this->url('device', ['action'=>'delete', 'id'=>$device->id]);?>">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        Delete</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>


<div class="row">
    <div class="col-md-12" id="map-container" style="height: 300px">
    </div>
</div>

<script type="text/javascript"
        src='http://maps.google.com/maps/api/js?sensor=false&libraries=places'></script>
<script src="<?php echo $this->basePath(
    '/js/jquery.googlemap.js'
); ?>"></script>

<script>
$(function () {
    var map = $("#map-container").googleMap();
    <?php $this->devices->current(); foreach($this->devices as $device):?>
    <?php if ($device):?>
    map.addMarker({
        coords: [<?php echo $device->lat; ?>, <?php echo $device->lng; ?>]
    });
    <?php endif; ?>
    <?php endforeach; ?>
});
</script>